client/app/dojo/bindings/contracts.gen.ts
client/app/dojo/bindings/models.gen.ts
client/package.json
client/pnpm-lock.yaml

fixed dojo schema error

---

engine/dojo_dev.toml
engine/dojo_release.toml
engine/manifest_dev.json

fixed sozo migrate errors

---

SETUP.md
package.json

setup file

---

client/app/play/page.tsx
client/package.json
client/pnpm-lock.yaml
client/tailwind.config.ts

Resolves #8 
Fixes:
- Fixed gameplay screen UI
- Added dark mode and light mode 
- Responsive UI
https://github.com/user-attachments/assets/dc252494-d544-441a-bf55-560b98fafcb8

Fixes gameplay ui screen

---

.github/workflows/update-contributors.yml
README.md

- Add GitHub Action workflow to track contributors
- Update README.md with Contributors section
- Automatically add contributor avatars when PRs are merged
Closes #25

feat: add automatic contributor updates to README

---

client/app/components/JoinRoomModal.tsx
client/app/globals.css
client/app/page.tsx
node_modules/.pnpm-workspace-state.json
pnpm-lock.yaml

added a modal on clicking join room

---

client/app/play/components/GameBoard.tsx
client/app/play/components/GameScores.tsx
client/app/play/components/GameStatus.tsx
client/app/play/components/Square.tsx
client/app/play/components/main.tsx
client/app/play/page.tsx

Chore: Refactor the gameplay page

---

erc/erc721/.tool-version
erc/erc721/Scarb.toml
erc/erc721/tests/test_contract.cairo

feat: erc721 test

---

.github/workflows/frontend-ci.yml

Github workflows for frontend 

---

engine/src/systems/start.cairo

closes #58 
This features introduces a new function to generate unique and random match ID for custom rooms.
The ID is generated by:
1. The caller address
2. The current block timestamp (on starknet new blocks take on average ~30s [based on this data](https://dune.com/caravanserai/starknet-overview))
In case the model id doesn't exist in this line:
```cairo
let board: Board = world.read_model(id);
```
It is cited in [Dojo's documentation](https://www.dojoengine.org/framework/world/api#read_model) that all the fields that are not key would be set to 0; so the `Board` `is_active` field would be false which is what we want.
And if there is already an active game at this ID, the ID is incremented by 1 to ensure uniqueness.
I have also made sure that there is no `.unwrap()` failures by using …

feat#58: generate random match id for custom rooms

---

engine/src/lib.cairo
engine/src/tests/test_play.cairo

feat: added tests for `play.cairo`

---

client/app/api/players.ts
client/app/models/player.ts
client/app/utils/db.ts
client/package.json
client/pnpm-lock.yaml

closes #67 
This PR adds the setup needed to fetch the list of players from a MongoDB database for the leaderboard page.  
- Added a GET API route to retrieve all players.  
- Route file: `client/app/api/players.ts`.  
- Connects to MongoDB, fetches players, and returns them as JSON.  
- Created a Mongoose model for players.  
- Fields: `address`, `winnings`, and `points`.  
- Model file: `client/app/models/Player.ts`.  
- Added a utility function to connect to MongoDB using Mongoose.  
- Function file: `client/app/utils/db.ts`.

FEAT: Create GET api route for user profiles

---

.github/workflows/contracts-ci.yml
engine/README.md
engine/Scarb.lock
engine/Scarb.toml

This PR updates the Dojo version to 1.2.1 and aligns all related dependencies accordingly. The following changes have been made:
- **Scarb.lock**:
- Upgraded Dojo version from 1.0.9 to 1.2.1
- Updated dependencies:
- `dojo_plugin` to 2.9.2
- `dojo_cairo_test` to 1.0.12
- **Scarb.toml**:
- Updated `cairo-version` to 2.9.2
- Upgraded Dojo version from 1.0.9 to 1.2.1
- Updated dev-dependencies:
- `dojo_cairo_test` to v1.2.1
- **README.md**:
- Added installation instructions for Dojo v1.2.1 under the Prerequisites section.

Feat: Upgrade Dojo to Version 1.2.1 and Update Dependencies

---

client/app/api/gameResult.ts
client/app/models/gameResult.ts

closes #70
**📋 Summary**
This **PR** adds the necessary setup to fetch game results from a **MongoDB database**, enabling the display of past game data on the results page.
**🔄 Changes
🟢 API Route**
1. Added a GET API route to retrieve all game results.
2. Route file: client/app/api/gameResults.ts
**Functionality:**
- Connects to MongoDB.
- Fetches all game results.
- Returns results as JSON.
- Handles errors and returns appropriate status codes.
**🟢 GameResult Model**
**Created a Mongoose model for game results.**
Fields:
- gameId (String, required)
- playerAddress (String, required)
- score (Number, required)
- result (String — win/lose/draw)
- timestamp (Date, defaults to current date)
**Model file: client/app/models/GameResult.ts**

Feat: Create a GET API route for game results

---

.github/workflows/contracts-ci.yml
erc/erc721/.tool-version
erc/erc721/Scarb.lock
erc/erc721/Scarb.toml
erc/erc721/tests/test_contract.cairo

closes #64
This PR contains an upgrade of starknet from 2.84 to 2.10.1 
- Was able to successfully build the project, fixing build errors by upgrading openzeppelin version to v1.0.0

feat: Bump erc721 to latest starknet version 2.10.1 #64

---

client/app/api/user.ts
client/app/models/user.ts

Create a POST API route for user profiles #66

---

client/app/api/game-results/gameResults.ts
client/app/api/user/[address].ts

⚡ Changes Made:
-Created API route in /api/user/[address] to fetch individual user profiles.
-Implemented error handling for:
-Missing or invalid address → Returns 400 Bad Request.
-Non-existing users → Returns 404 Not Found.
-Integrated database query using Mongoose for user data retrieval.
-Fixed import error in Issue #67.
Closes #68
Fixes #67

FEAT : Create GET API route for individual user profiles

---

erc/erc20/src/erc20.cairo
erc/erc20/tests/test_contract.cairo

Feat; Rewrite ERC20 contract

---

client/app/profile/[address]/loading.tsx
client/app/profile/[address]/page.tsx

feat: add profile page

---

engine/src/models.cairo
engine/src/systems/leave.cairo
engine/src/systems/play.cairo
engine/src/systems/read_board.cairo
engine/src/systems/start.cairo

Feat: Upgrade the matchmaking logic to support up to 9 players.

---

.github/workflows/contracts-ci.yml
.github/workflows/engine-ci.yml

Fix build errors

---

client/app/dojo/bindings/contracts.gen.ts
client/app/layout.tsx

fixed vercel error

---

engine/Scarb.toml
engine/dojo_sepolia.toml
sepolia.md

feat: Sepolia re-deployment

---

client/app/history/page.tsx

This PR implements the player match history dashboard UI as specified in issue #134. The dashboard displays a player's match history with visual indicators for wins, losses, and draws.
- Responsive design that works on mobile, tablet, and desktop screens
- Color-coded rows for match results:
- Green for wins
- Red for losses
- Yellow for draws
- Displays complete match data, including
- Match result
- Opponent name
- Winnings
- Points gained/lost
- Match date
- Pagination support for browsing through match history
- Loading state while data is being fetched
- Empty state when no matches are available
- Adaptive layout: card view on mobile, table view on desktop
- Currently using mock data for demonstration purposes
- Actual API integration will be implemented in a follow-up PR
- Follows …

build the UI for History dashboard #134

---

erc/erc721/src/achievement_nft.cairo
erc/erc721/src/lib.cairo
erc/erc721/tests/test_achievment_nft.cairo

closes #137 
Implements ERC721-based NFT badges to represent and reward user achievements.

feat: implement ERC721 based NFT badges for achievements

---

client/app/play/components/GameStatus.tsx
client/app/play/page.tsx

closes #136 
- Adds an interval based mechanism to track move timers in `app/play/page.tsx`
- Adds a template UI change to display time remaining.
This is UI of the move timer ticking down
https://github.com/user-attachments/assets/ea9163db-9d4e-4f16-9af7-4d3ebcdefe7c
This is the result of the game

Implement timer-based penalty system

---

client/app/friends/components/EmptyState.tsx
client/app/friends/components/FriendRequests.tsx
client/app/friends/components/FriendsList.tsx
client/app/friends/components/LoadingState.tsx
client/app/friends/components/SearchBar.tsx
client/app/friends/hooks/useFriends.tsx
client/app/friends/page.tsx
client/app/layout.tsx
client/app/page.tsx
client/tsconfig.json

closes #132
This PR implements the Friends page UI with the following features:
- Created dedicated `/friends` route with tab-based navigation
- Implemented Friends list with avatar, username, and online status indicators
- Added pending friend requests section with Accept/Reject functionality
- Integrated search functionality for filtering friends by username
- Designed responsive UI with consistent styling matching the app's design system
- `FriendsList` - Displays current friends with online status indicators
- `FriendRequests` - Shows incoming friend requests with action buttons
- `SearchBar` - Provides real-time filtering capability
- `EmptyState` - Contextual empty state messaging
- `LoadingState` - Skeleton loading UI for better UX
- Used custom hook (`useFriends`) for data …

PR for Add friends page

---

client/app/components/Header.tsx
client/app/components/JoinRoomModal.tsx
client/app/context/WalletContext.tsx
client/app/dojo/dojo.config.ts
client/app/layout.tsx
client/app/page.tsx
client/app/play/page.tsx
client/package.json

closes #135 
Please be aware that **this feature branch (`feat/135-room-join-create`) was branched off the `stake` branch, not the main development branch (e.g., `main` or `dev`).**
**Reasoning:**
The core operations for creating and joining rooms require interaction with the Dojo SDK. These interactions **mandate** the inclusion of the user's wallet account information (the `account` parameter). The necessary logic for wallet connection, obtaining the user's `account`, and managing related state was implemented or is under development in the `stake` branch.
To avoid reimplementing wallet connection and account management functionality and to directly leverage the existing work in the `stake` branch, this branch was created from `stake`. This ensures that the required `account` parameter …

feat: Implement room creation and joining functionality
